import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { AlignCenter, AlignLeft, AlignRight, Brush, ChevronRight, Disc3, Globe, Link2, MapPin, Music, Palette, Plus, Save, Smile, Star, Trash2, Type, Undo2, Users, X } from 'lucide-react';
import { motion } from 'framer-motion';
import { userService } from '../../services/api';

const audiences = [{ value: 'everyone', label: 'Everyone', Icon: Globe }, { value: 'followers', label: 'Followers', Icon: Users }, { value: 'close_friends', label: 'Close friends', Icon: Star }];
const fonts = ['sans-serif', 'serif', 'cursive', 'monospace'];
const colors = ['#ffffff', '#f43f5e', '#facc15', '#22c55e', '#38bdf8'];
const emoji = ['😀', '😍', '🔥', '✨', '😂', '💖', '👏', '🎉'];
const tracks = [
  { id: 'sunrise', title: 'Sunrise Circuit', artist: 'Pixora Sounds', category: 'Trending', notes: [261, 329, 392] },
  { id: 'breezy', title: 'Breezy Afternoon', artist: 'Pixora Sounds', category: 'Chill', notes: [220, 277, 330] },
  { id: 'neon', title: 'Neon Pop', artist: 'Pixora Sounds', category: 'Pop', notes: [330, 415, 494] },
  { id: 'coffee', title: 'Coffee Tape', artist: 'Pixora Sounds', category: 'Lo-fi', notes: [174, 220, 262] },
  { id: 'ambient', title: 'Open Skies', artist: 'Pixora Sounds', category: 'Instrumental', notes: [196, 247, 294] },
  { id: 'pulse', title: 'Night Pulse', artist: 'Pixora Sounds', category: 'Trending', notes: [247, 294, 370] },
];
const makeElement = (type, data = {}) => ({ id: crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`, type, x: 50, y: 50, width: type === 'text' ? 48 : type === 'drawing' ? 100 : 28, height: type === 'drawing' ? 100 : 14, rotation: 0, zIndex: Date.now(), data });

const Element = ({ element, selected, onSelect, onMove }) => {
  const start = useRef(null);
  const content = element.type === 'text' ? <span style={{ color: element.data.color, fontFamily: element.data.font, textAlign: element.data.align, background: element.data.background, fontSize: `${element.data.size || 26}px` }}>{element.data.text}</span>
    : element.type === 'drawing' ? <svg viewBox="0 0 100 100" className="h-full w-full overflow-visible">{element.data.strokes?.map((stroke, index) => <polyline key={index} points={stroke.points} fill="none" stroke={stroke.color} strokeWidth={stroke.size} strokeLinecap="round" strokeLinejoin="round" />)}</svg>
    : element.type === 'mention' ? <span className="rounded-full bg-primary px-3 py-1 font-semibold text-white">@{element.data.username}</span>
    : element.type === 'location' ? <span className="rounded-full bg-white px-3 py-1 font-semibold text-black">📍 {element.data.label}</span>
    : element.type === 'link' ? <span className="rounded-full bg-blue-500 px-3 py-1 font-semibold text-white">🔗 {element.data.label}</span>
    : element.type === 'music' ? <span className="rounded-full bg-fuchsia-600 px-3 py-1 text-white">♫ {element.data.title}</span>
    : element.type === 'gif' ? <img src={element.data.url} alt="GIF sticker" className="h-full w-full object-contain" />
    : <span className="text-4xl">{element.data.emoji}</span>;
  return <div role="button" tabIndex={0} aria-label={`${element.type} layer`} onPointerDown={(event) => { event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); start.current = { x: event.clientX, y: event.clientY, elementX: element.x, elementY: element.y }; onSelect(element.id); }} onPointerMove={(event) => { if (!start.current) return; onMove(element.id, { x: Math.max(0, Math.min(100, start.current.elementX + (event.clientX - start.current.x) / 3)), y: Math.max(0, Math.min(100, start.current.elementY + (event.clientY - start.current.y) / 5)) }); }} onPointerUp={() => { start.current = null; }} className={`absolute cursor-move select-none touch-none ${selected ? 'ring-2 ring-white ring-offset-2 ring-offset-black' : ''}`} style={{ left: `${element.x}%`, top: `${element.y}%`, width: `${element.width}%`, minHeight: `${element.height}%`, transform: `translate(-50%, -50%) rotate(${element.rotation}deg)`, zIndex: element.zIndex }}>{content}</div>;
};

export const StoryEditor = ({ file, preview, draft, initialElements, onPublish, onSaveDraft, onDiscard, onCancel, isUploading }) => {
  const [audience, setAudience] = useState(draft?.audience || 'everyone');
  const [elements, setElements] = useState(() => {
    const base = draft?.elements || [];
    return initialElements?.length ? [...base, ...initialElements] : base;
  });
  const [active, setActive] = useState(null);
  const [selected, setSelected] = useState(null);
  const [text, setText] = useState(''); const [textColor, setTextColor] = useState('#ffffff'); const [textAlign, setTextAlign] = useState('center'); const [textBg, setTextBg] = useState('transparent');
  const [ink, setInk] = useState('#ffffff'); const [brushSize, setBrushSize] = useState(3); const [drawing, setDrawing] = useState(null);
  const [mentionQuery, setMentionQuery] = useState(''); const [mentions, setMentions] = useState([]); const [musicCategory, setMusicCategory] = useState('All'); const [musicSearch, setMusicSearch] = useState('');
  const stageRef = useRef(null); const pointerId = useRef(null); const pointsRef = useRef(''); const audioRef = useRef(null);
  const isVideo = file?.type?.startsWith('video') || draft?.media?.mediaType === 'video'; const source = preview || draft?.media?.url;
  const requestClose = useCallback(() => { if (!elements.length || window.confirm('Discard this story draft and your unsaved edits?')) onCancel(); }, [elements.length, onCancel]);
  useEffect(() => { const close = (event) => event.key === 'Escape' && requestClose(); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [requestClose]);
  useEffect(() => { if (active !== 'mention' || !mentionQuery.trim()) return; const timeout = setTimeout(() => userService.search(mentionQuery).then((data) => setMentions(data.users || [])).catch(() => setMentions([])), 250); return () => clearTimeout(timeout); }, [active, mentionQuery]);
  useEffect(() => () => audioRef.current?.close?.(), []);
  const add = (type, data) => { const layer = makeElement(type, data); setElements((items) => [...items, layer]); setSelected(layer.id); };
  const update = (id, patch) => setElements((items) => items.map((element) => element.id === id ? { ...element, ...patch } : element));
  const selectedElement = elements.find((element) => element.id === selected);
  const point = (event) => { const box = stageRef.current.getBoundingClientRect(); return `${(((event.clientX - box.left) / box.width) * 100).toFixed(2)},${(((event.clientY - box.top) / box.height) * 100).toFixed(2)}`; };
  const beginStroke = (event) => { if (active !== 'draw' || event.button > 0 || !stageRef.current) return; event.preventDefault(); pointerId.current = event.pointerId; event.currentTarget.setPointerCapture(event.pointerId); pointsRef.current = point(event); setDrawing({ color: ink, size: brushSize, points: pointsRef.current }); };
  const continueStroke = (event) => { if (pointerId.current !== event.pointerId || !drawing) return; event.preventDefault(); const events = event.getCoalescedEvents?.() || [event]; const points = events.map(point).join(' '); pointsRef.current = `${pointsRef.current} ${points}`; setDrawing((stroke) => stroke ? { ...stroke, points: pointsRef.current } : stroke); };
  const endStroke = (event) => { if (pointerId.current !== event.pointerId) return; pointerId.current = null; if (pointsRef.current) add('drawing', { strokes: [{ color: ink, size: brushSize, points: pointsRef.current }] }); pointsRef.current = ''; setDrawing(null); };
  const playPreview = (track) => { audioRef.current?.close?.(); const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return; const context = new AudioContext(); audioRef.current = context; track.notes.forEach((frequency, index) => { const osc = context.createOscillator(); const gain = context.createGain(); osc.type = 'sine'; osc.frequency.value = frequency; gain.gain.setValueAtTime(0.0001, context.currentTime + index * .32); gain.gain.exponentialRampToValueAtTime(.12, context.currentTime + index * .32 + .04); gain.gain.exponentialRampToValueAtTime(.0001, context.currentTime + index * .32 + .3); osc.connect(gain).connect(context.destination); osc.start(context.currentTime + index * .32); osc.stop(context.currentTime + index * .32 + .32); }); };
  const selectMusic = (track) => { setElements((items) => [...items.filter((item) => item.type !== 'music'), makeElement('music', { id: track.id, title: track.title, artist: track.artist, category: track.category, provider: 'pixora-synthetic-preview' })]); setActive(null); };
  const shownTracks = tracks.filter((track) => (musicCategory === 'All' || track.category === musicCategory) && `${track.title} ${track.artist}`.toLowerCase().includes(musicSearch.toLowerCase()));
  const runPublish = () => onPublish({ file, draftId: draft?._id, audience, elements });

  return createPortal(<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[9999] bg-black text-white">
    <div ref={stageRef} className="absolute inset-0 overflow-hidden">{isVideo ? <video src={source} autoPlay loop muted playsInline className="h-full w-full object-contain" /> : <img src={source} alt="Story preview" className="h-full w-full object-contain" draggable={false} />}<div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/45 via-transparent to-black/60" />{[...elements].sort((a, b) => a.zIndex - b.zIndex).map((element) => <Element key={element.id} element={element} selected={selected === element.id} onSelect={setSelected} onMove={(id, patch) => update(id, patch)} />)}{active === 'draw' && <svg className="absolute inset-0 z-10 h-full w-full touch-none" viewBox="0 0 100 100" preserveAspectRatio="none" onPointerDown={beginStroke} onPointerMove={continueStroke} onPointerUp={endStroke} onPointerCancel={endStroke}><rect width="100" height="100" fill="transparent" />{drawing && <polyline points={drawing.points} fill="none" stroke={drawing.color} strokeWidth={drawing.size} strokeLinecap="round" strokeLinejoin="round" />}</svg>}</div>
    <header className="absolute inset-x-0 top-0 z-20 flex items-center justify-between p-4 pt-[max(1rem,env(safe-area-inset-top))]"><button onClick={requestClose} disabled={isUploading} className="rounded-full bg-black/45 p-2.5" aria-label="Close story editor"><X /></button><span className="font-logo text-lg">Pixora</span><div className="w-10" /></header>
    <aside className="absolute bottom-28 left-3 z-20 flex max-w-[calc(100vw-1.5rem)] gap-2 overflow-x-auto rounded-2xl bg-black/60 p-2 backdrop-blur md:bottom-auto md:left-auto md:right-3 md:top-1/2 md:flex-col md:-translate-y-1/2">{[['text', Type], ['draw', Brush], ['emoji', Smile], ['gif', Disc3], ['mention', Plus], ['location', MapPin], ['link', Link2], ['music', Music]].map(([name, Icon]) => <button key={name} onClick={() => { setSelected(null); setActive((current) => current === name ? null : name); }} className={`rounded-xl p-2.5 ${active === name ? 'bg-white text-black' : 'bg-white/10'}`} aria-pressed={active === name} aria-label={`Add ${name}`}><Icon className="h-5 w-5" /></button>)}</aside>
    {active && <section className="absolute bottom-28 left-3 right-3 z-30 mx-auto max-w-md rounded-2xl bg-black/90 p-3 shadow-2xl backdrop-blur md:bottom-4 md:right-20 md:left-auto">
      {active === 'text' && <div className="space-y-2"><input autoFocus value={text} onChange={(event) => setText(event.target.value)} placeholder="Write something" className="w-full rounded-lg bg-white/15 px-3 py-2 outline-none" /><div className="flex flex-wrap gap-2">{fonts.map((font) => <button key={font} onClick={() => add('text', { text: text || 'Text', color: textColor, font, align: textAlign, background: textBg, size: 26 })} className="rounded bg-white/15 px-2 py-1 text-xs" style={{ fontFamily: font }}>{font}</button>)}{[AlignLeft, AlignCenter, AlignRight].map((Icon, index) => <button key={index} onClick={() => setTextAlign(['left', 'center', 'right'][index])} className="rounded bg-white/15 p-1"><Icon className="h-4" /></button>)}</div><div className="flex gap-2">{colors.map((color) => <button key={color} onClick={() => setTextColor(color)} className="h-6 w-6 rounded-full ring-1 ring-white/40" style={{ background: color }} />)}<button onClick={() => setTextBg(textBg === 'transparent' ? 'rgba(0,0,0,.45)' : 'transparent')} className="rounded bg-white/15 px-2 text-xs">Background</button></div></div>}
      {active === 'draw' && <div className="flex flex-wrap items-center gap-3"><Palette style={{ color: ink }} /><input aria-label="Brush colour" type="color" value={ink} onChange={(event) => setInk(event.target.value)} /><input aria-label="Brush size" type="range" min="1" max="12" value={brushSize} onChange={(event) => setBrushSize(Number(event.target.value))} /><span className="text-xs text-white/70">Press and drag on the story</span><button onClick={() => setElements((items) => items.filter((item) => item.type !== 'drawing'))} className="text-xs">Clear</button><button onClick={() => setElements((items) => { const last = [...items].reverse().find((item) => item.type === 'drawing'); return last ? items.filter((item) => item.id !== last.id) : items; })} className="text-xs">Undo</button></div>}
      {active === 'emoji' && <div className="flex flex-wrap gap-2">{emoji.map((value) => <button key={value} onClick={() => add('emoji', { emoji: value })} className="text-2xl">{value}</button>)}</div>}
      {active === 'gif' && <div className="space-y-2"><p className="text-xs text-white/70">Paste a GIF URL (GIPHY/Tenor or your hosted GIF).</p><input onKeyDown={(event) => { if (event.key === 'Enter' && event.currentTarget.value) add('gif', { url: event.currentTarget.value }); }} placeholder="https://…gif" className="w-full rounded bg-white/15 px-3 py-2 text-sm" /></div>}
      {active === 'mention' && <div><input value={mentionQuery} onChange={(event) => setMentionQuery(event.target.value)} placeholder="Search people" className="w-full rounded bg-white/15 px-3 py-2 text-sm" />{mentions.map((person) => <button key={person._id} onClick={() => add('mention', { username: person.username, userId: person._id })} className="block w-full py-2 text-left text-sm">@{person.username}</button>)}</div>}
      {active === 'music' && <div className="space-y-3"><div className="flex gap-2 overflow-x-auto">{['All', 'Trending', 'Chill', 'Pop', 'Lo-fi', 'Instrumental'].map((category) => <button key={category} onClick={() => setMusicCategory(category)} className={`whitespace-nowrap rounded-full px-3 py-1 text-xs ${musicCategory === category ? 'bg-white text-black' : 'bg-white/15'}`}>{category}</button>)}</div><input value={musicSearch} onChange={(event) => setMusicSearch(event.target.value)} placeholder="Search sounds" className="w-full rounded bg-white/15 px-3 py-2 text-sm" />{elements.some((item) => item.type === 'music') && <button onClick={() => setElements((items) => items.filter((item) => item.type !== 'music'))} className="text-xs text-red-300">Remove selected music</button>}<div className="max-h-48 space-y-1 overflow-y-auto">{shownTracks.map((track) => <div key={track.id} className="flex items-center gap-2 rounded-lg bg-white/10 p-2"><button onClick={() => playPreview(track)} className="rounded-full bg-white/15 px-2 py-1 text-xs">Preview</button><button onClick={() => selectMusic(track)} className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-medium">{track.title}</p><p className="text-xs text-white/60">{track.category} · {track.artist}</p></button></div>)}</div><p className="text-[10px] text-white/50">Synthetic Pixora Sounds are generated in-browser for copyright-safe development previews.</p></div>}
      {['location', 'link'].includes(active) && <input autoFocus onKeyDown={(event) => { if (event.key !== 'Enter' || !event.currentTarget.value) return; add(active, active === 'location' ? { label: event.currentTarget.value } : { label: event.currentTarget.value, url: event.currentTarget.value }); }} placeholder={`Add ${active}`} className="w-full rounded bg-white/15 px-3 py-2 text-sm" />}
    </section>}
    {selectedElement && active !== 'draw' && <div className="absolute right-3 top-20 z-30 flex flex-col gap-2 rounded-xl bg-black/70 p-2"><button onClick={() => update(selected, { width: Math.min(100, selectedElement.width + 5), height: Math.min(100, selectedElement.height + 3) })} aria-label="Resize layer"><Plus /></button><button onClick={() => update(selected, { rotation: selectedElement.rotation + 15 })} aria-label="Rotate layer"><Undo2 className="rotate-90" /></button><button onClick={() => update(selected, { zIndex: selectedElement.zIndex + 10000000000000 })} aria-label="Bring layer forward">↑</button><button onClick={() => update(selected, { zIndex: selectedElement.zIndex - 10000000000000 })} aria-label="Send layer backward">↓</button><button onClick={() => { setElements((items) => items.filter((item) => item.id !== selected)); setSelected(null); }} aria-label="Delete layer"><Trash2 /></button></div>}
    <footer className="absolute inset-x-0 bottom-0 z-20 p-4 pb-[max(1.5rem,env(safe-area-inset-bottom))] bg-gradient-to-t from-black/85 to-transparent"><div className="mx-auto flex max-w-xl items-center gap-2"><select value={audience} onChange={(event) => setAudience(event.target.value)} className="rounded-full bg-black/50 px-3 py-2 text-sm">{audiences.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}</select>{draft && <button onClick={() => window.confirm('Discard this saved draft?') && onDiscard?.()} disabled={isUploading} className="rounded-full bg-red-500/70 px-3 py-2 text-sm">Discard</button>}<button onClick={() => onSaveDraft?.({ file, draftId: draft?._id, audience, elements })} disabled={isUploading} className="ml-auto rounded-full bg-white/15 px-3 py-2 text-sm"><Save className="mr-1 inline h-4" />Save draft</button><button onClick={runPublish} disabled={isUploading} className="rounded-full bg-primary px-4 py-2 font-semibold">{isUploading ? 'Saving…' : 'Share'} <ChevronRight className="inline h-4" /></button></div></footer>
  </motion.div>, document.body);
};
